# prefixキーをC-qに変更する
set -g prefix C-q
unbind C-b

# ペイン分割
bind | split-window -h
bind - split-window -v

# 256色モード
set-option -g default-terminal screen-256color

# ステータスライン
setw -g status-style fg=colour255,bg=colour234
setw -g window-status-current-format '#[bg=colour1,fg=colour255]#{?client_prefix,#[bg=colour2],} #I #W '

# マウス
set -g mouse on
unbind -T copy-mode MouseDragEnd1Pane
bind-key -T copy-mode Enter send-keys -X copy-pipe-and-cancel "tmux copy-buffer"
bind-key -T copy-mode Enter send-keys -X copy-pipe "tmux copy-buffer"
